package com.example.sibo;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.SearchView;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {

    SearchView searchView;
    ListView myListView;

    ArrayList<String> arrayList;
    CustomListAdapter adapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        searchView = findViewById(R.id.searchView);
        myListView = findViewById(R.id.listView);

        arrayList = new ArrayList<>();
        arrayList.add("Acesulfam K;Low");
        arrayList.add("Agar-Agar;Low");
        arrayList.add("Agawa;High");
        arrayList.add("Ananas (Suszony);High");
        arrayList.add("Ananas;Low");
        arrayList.add("Anyż Gwiazdkowaty;Low");
        arrayList.add("Arbuzy;High");
        arrayList.add("Asafetyda W Proszku;Low");
        arrayList.add("Aspartam;Low");
        arrayList.add("Awokado;High");
        arrayList.add("Bakłażan;Low");
        arrayList.add("Banan (Dojrzały);High");
        arrayList.add("Banan (Niedojrzały);Low");
        arrayList.add("Banan (Suszony);Low");
        arrayList.add("Batonik Zbożowy;High");
        arrayList.add("Bazylia Tajska;Low");
        arrayList.add("Bazylia;Low");
        arrayList.add("Biała Cebula;High");
        arrayList.add("Białko Grochu;Low");
        arrayList.add("Biały Chleb Na Zakwasie;Medium");
        arrayList.add("Biały Cukier;Low");
        arrayList.add("Biały Ziemniak;Low");
        arrayList.add("Bita Śmietana;High");
        arrayList.add("Błyskawiczna Galaretka;Low");
        arrayList.add("Boczek;Low");
        arrayList.add("Boćwina;Low");
        arrayList.add("Bok Choy;Low");
        arrayList.add("Boysenberry;High");
        arrayList.add("Bób;High");
        arrayList.add("Brandy;Low");
        arrayList.add("Brązowy Cukier;Low");
        arrayList.add("Brokuły (Całe);High");
        arrayList.add("Brokuły (Głowy);Low");
        arrayList.add("Brokuły (Łodygi);High");
        arrayList.add("Brukiew;Low");
        arrayList.add("Brukselki;High");
        arrayList.add("Brzoskwinie;High");
        arrayList.add("Bulgur;High");
        arrayList.add("Bułka Tarta Panko;Low");
        arrayList.add("Burak (Marynowany);Low");
        arrayList.add("Buraki Ćwikłowe;High");
        arrayList.add("Buraki;High");
        arrayList.add("Cebula Hiszpańska (Czerwona Cebula);High");
        arrayList.add("Cebule;High");
        arrayList.add("Cebulki Konserwowe;Low");
        arrayList.add("Chili Czerwone;Low");
        arrayList.add("Chili W Proszku;Low");
        arrayList.add("Chili Zielone;Low");
        arrayList.add("Chipsy Tortilla;Low");
        arrayList.add("Chipsy;Low");
        arrayList.add("Chleb Kamut Na Zakwasie;High");
        arrayList.add("Chleb Kukurydziany;Low");
        arrayList.add("Chleb Naan;High");
        arrayList.add("Chleb Orkiszowy Na Zakwasie;Low");
        arrayList.add("Chleb Owsiany Na Zakwasie;Medium");
        arrayList.add("Chleb Pszeniczny;High");
        arrayList.add("Chleb Roti;High");
        arrayList.add("Chleb Żytni Na Zakwasie;High");
        arrayList.add("Chleb Żytni;High");
        arrayList.add("Chlebowiec Różnolistny;Low");
        arrayList.add("Chrupki Żytnie;High");
        arrayList.add("Chryzantemy;Low");
        arrayList.add("Chutney;Low");
        arrayList.add("Ciasteczka Ryżowe;Low");
        arrayList.add("Ciasto Filo;Medium");
        arrayList.add("Ciecierzyca Konserwowa;Medium");
        arrayList.add("Ciecierzyca (Maksymalnie 1/4 Szklanki);Low");
        arrayList.add("Ciecierzyca;Medium");
        arrayList.add("Cienka Kukurydza;Medium");
        arrayList.add("Creme Fraiche;Low");
        arrayList.add("Cukier - Sacharoza;Low");
        arrayList.add("Cukier Granulowany;Low");
        arrayList.add("Cukier Kokosowy;Low");
        arrayList.add("Cukier Palmowy;Low");
        arrayList.add("Cukier Puder;Low");
        arrayList.add("Cukinia;Low");
        arrayList.add("Curry W Proszku;Low");
        arrayList.add("Custard;High");
        arrayList.add("Cydr;High");
        arrayList.add("Cynamon;Low");
        arrayList.add("Cytryny;Low");
        arrayList.add("Czarna Fasola;High");
        arrayList.add("Czarna Kawa;Low");
        arrayList.add("Czekolada Biała;Medium");
        arrayList.add("Czekolada Ciemna;Low");
        arrayList.add("Czekolada Do Picia W Proszku;Low");
        arrayList.add("Czekolada Mleczna (Maks. 4 Kostki);Low");
        arrayList.add("Czerwona Fasola;High");
        arrayList.add("Czerwona Papryka;Low");
        arrayList.add("Czerwone Wino;Low");
        arrayList.add("Czerwony Ocet Winny;Low");
        arrayList.add("Czosnek Czarny;High");
        arrayList.add("Czosnek;High");
        arrayList.add("Czysty Syrop Klonowy;Low");
        arrayList.add("Daikon;Low");
        arrayList.add("Daktyle;High");
        arrayList.add("Dip Kawiorowy;Medium");
        arrayList.add("Dip Tzatziki;High");
        arrayList.add("Drób;Low");
        arrayList.add("Durian;Low");
        arrayList.add("Dymka (Biała Część);High");
        arrayList.add("Dymka (Zielona Część);Low");
        arrayList.add("Dynia Japońska (Kabocha);Low");
        arrayList.add("Dynia Piżmowa;Medium");
        arrayList.add("Dynia;Low");
        arrayList.add("Dżem Jagodowy;High");
        arrayList.add("Dżem (Mieszanka Jagód);High");
        arrayList.add("Dżem Truskawkowy;Low");
        arrayList.add("Edamame (Soja);Low");
        arrayList.add("Esencja Waniliowa;Low");
        arrayList.add("Espresso;Low");
        arrayList.add("Estragon;Low");
        arrayList.add("Falafel;High");
        arrayList.add("Fasola Borlotti;High");
        arrayList.add("Fasola Canneliniego;High");
        arrayList.add("Fasola Garbanzo;Medium");
        arrayList.add("Fasola Maślana;High");
        arrayList.add("Fasola Mung (Gotowana);High");
        arrayList.add("Fasola Mung (Kiełki);Low");
        arrayList.add("Fasola Np. Czarny, Szeroki, Nerkowy, Lima, Sojowy;High");
        arrayList.add("Fasola Pinto;High");
        arrayList.add("Fasola Yardlong;Low");
        arrayList.add("Fasolka Adzuki;High");
        arrayList.add("Fasolka Szparagowa;High");
        arrayList.add("Fasolki Sojowe;High");
        arrayList.add("Fasolki;High");
        arrayList.add("Feijoa (Gujawa Ananasowa);High");
        arrayList.add("Feta;Low");
        arrayList.add("Figi;High");
        arrayList.add("Filtrowana Kawa;Low");
        arrayList.add("Freekeh;High");
        arrayList.add("Galangal;Low");
        arrayList.add("Gałka Muszkatołowa;Low");
        arrayList.add("Ghee;Low");
        arrayList.add("Gin;Low");
        arrayList.add("Glukoza;Low");
        arrayList.add("Gnocchi Pszenne;High");
        arrayList.add("Gnocchi;High");
        arrayList.add("Goraka;Low");
        arrayList.add("Gorąca Czekolada;Low");
        arrayList.add("Gorzki Melon;High");
        arrayList.add("Gotukala (Gotu Kola);Low");
        arrayList.add("Goździki;Low");
        arrayList.add("Granat;High");
        arrayList.add("Granola;High");
        arrayList.add("Grejpfrut;Low");
        arrayList.add("Groch Łuskany;High");
        arrayList.add("Groszek Cukrowy;High");
        arrayList.add("Groszek Ogrodowy;High");
        arrayList.add("Gruszki;High");
        arrayList.add("Gryka;Low");
        arrayList.add("Grzyb Boczniak;Low");
        arrayList.add("Grzyb Borowik;High");
        arrayList.add("Grzyb Czarny;Low");
        arrayList.add("Grzyb Enoki;High");
        arrayList.add("Grzyb Młode Pieczarki;High");
        arrayList.add("Grzyb Pieczarki;Low");
        arrayList.add("Grzyb Portobello;High");
        arrayList.add("Grzyb Shiitake;High");
        arrayList.add("Grzyb Shimeji;Low");
        arrayList.add("Grzyby;High");
        arrayList.add("Gujawa (Dojrzała);Low");
        arrayList.add("Gujawa (Niedojrzała);High");
        arrayList.add("Guma Ksantanowa;Low");
        arrayList.add("Herbata Biała;Low");
        arrayList.add("Herbata Chryzantema;Medium");
        arrayList.add("Herbata Czai;High");
        arrayList.add("Herbata Czarna;Low");
        arrayList.add("Herbata Czerwona;Low");
        arrayList.add("Herbata Kombucha;High");
        arrayList.add("Herbata Miętowa;Low");
        arrayList.add("Herbata Mniszek Lekarski;Medium");
        arrayList.add("Herbata Oolong;High");
        arrayList.add("Herbata Rooibos;Low");
        arrayList.add("Herbata Rumiankowa;High");
        arrayList.add("Herbata Z Kopru Włoskiego;High");
        arrayList.add("Herbata Zielona;Low");
        arrayList.add("Herbata Ziołowa (Mocna);High");
        arrayList.add("Herbata Ziołowa (Słaba);Low");
        arrayList.add("Herbata Ziołowa;Medium");
        arrayList.add("Hummus;High");
        arrayList.add("Imbir;Low");
        arrayList.add("Indyk;Low");
        arrayList.add("Inne Soki Owocowe;High");
        arrayList.add("Inulina;High");
        arrayList.add("Izomalt;High");
        arrayList.add("Jabłka;High");
        arrayList.add("Jagnięcina;Low");
        arrayList.add("Jagody Goji;High");
        arrayList.add("Jagody;Low");
        arrayList.add("Jajka;Low");
        arrayList.add("Jarmuż;Low");
        arrayList.add("Jeżyny;High");
        arrayList.add("Jęczmień Perłowy;High");
        arrayList.add("Jęczmień;High");
        arrayList.add("Jicama;Low");
        arrayList.add("Jogurt Bez Laktozy;Low");
        arrayList.add("Jogurt Grecki;High");
        arrayList.add("Jogurt Kokosowy;Low");
        arrayList.add("Jogurt Mleko Kozie;High");
        arrayList.add("Jogurt Naturalny;High");
        arrayList.add("Jogurt;High");
        arrayList.add("Kabaczek Pattypan;Low");
        arrayList.add("Kabaczek;Low");
        arrayList.add("Kai Lan;Low");
        arrayList.add("Kakao W Proszku;Low");
        arrayList.add("Kakao;Medium");
        arrayList.add("Kalafior;High");
        arrayList.add("Kalarepa;Low");
        arrayList.add("Kantalupa;Low");
        arrayList.add("Kapary;Low");
        arrayList.add("Kapusta Chińska;Low");
        arrayList.add("Kapusta Czerwona;Low");
        arrayList.add("Kapusta Kiszona;High");
        arrayList.add("Kapusta Pekińska;Low");
        arrayList.add("Kapusta Włoska;High");
        arrayList.add("Kapusta Zwyczajna;Low");
        arrayList.add("Kapusta;Low");
        arrayList.add("Karambola (Owoc Gwiaździsty);Low");
        arrayList.add("Karczochy;High");
        arrayList.add("Kardamon;Low");
        arrayList.add("Kasza Gryczana;Medium");
        arrayList.add("Kasza Owsiana;Low");
        arrayList.add("Kaszka Manna;High");
        arrayList.add("Kasztany Wodne;Low");
        arrayList.add("Kasztany;Low");
        arrayList.add("Kawa Rozpuszczalna;High");
        arrayList.add("Kawa Z Mlekiem;High");
        arrayList.add("Kefir;Medium");
        arrayList.add("Kiełbaski (Sprawdź Skład);High");
        arrayList.add("Kiełki Bambusa;Low");
        arrayList.add("Kiełki Fasoli;Low");
        arrayList.add("Kimchi;High");
        arrayList.add("Kiwi;Low");
        arrayList.add("Klementynki;Low");
        arrayList.add("Kminek;Low");
        arrayList.add("Kolczoch;High");
        arrayList.add("Kolendra;Low");
        arrayList.add("Komosa Ryżowa Biała;Low");
        arrayList.add("Komosa Ryżowa Czarna;Low");
        arrayList.add("Komosa Ryżowa Czerwona;Low");
        arrayList.add("Komosa Ryżowa Mielona;Low");
        arrayList.add("Komosa Ryżowa;Low");
        arrayList.add("Koncentrat Pomidorowy;High");
        arrayList.add("Koper Włoski;Medium");
        arrayList.add("Koperek;Low");
        arrayList.add("Korzeń Lotosu;High");
        arrayList.add("Kozieradka;Low");
        arrayList.add("Krem Kokosowy;Low");
        arrayList.add("Krewetki;Low");
        arrayList.add("Kruche Ciastko;Medium");
        arrayList.add("Ksylitol;High");
        arrayList.add("Kukurydza;Low");
        arrayList.add("Kumkwaty;Low");
        arrayList.add("Kurczak;Low");
        arrayList.add("Kurkuma;Low");
        arrayList.add("Kuskus;High");
        arrayList.add("Kwas Chlebowy;Low");
        arrayList.add("Liczi;High");
        arrayList.add("Limonki;Low");
        arrayList.add("Liście Curry;Low");
        arrayList.add("Liście Cykorii;Low");
        arrayList.add("Liście Endywii;Low");
        arrayList.add("Liście Laurowe;Low");
        arrayList.add("Liście Limonki Kaffir;Low");
        arrayList.add("Lody;Medium");
        arrayList.add("Longana;Medium");
        arrayList.add("Lucerna;Low");
        arrayList.add("Lukrecja;Low");
        arrayList.add("Łosoś;Low");
        arrayList.add("Majonez;Low");
        arrayList.add("Makaron Bezglutenowy;Low");
        arrayList.add("Makaron Orkiszowy;High");
        arrayList.add("Makaron Pszenny;High");
        arrayList.add("Makaron Quinoa;Low");
        arrayList.add("Makaron Ryżowy;Low");
        arrayList.add("Makaron Soba;Low");
        arrayList.add("Makaron Wermiszelowy;Low");
        arrayList.add("Makaron Z Ciecierzycy;Low");
        arrayList.add("Makaron Z Wodorostów;Low");
        arrayList.add("Mak;Low");
        arrayList.add("Maliny;Low");
        arrayList.add("Maltitol;High");
        arrayList.add("Mandarynka;Low");
        arrayList.add("Mange Tout;High");
        arrayList.add("Mango;High");
        arrayList.add("Mangostan Właściwy;Low");
        arrayList.add("Maniok;High");
        arrayList.add("Mannitol;High");
        arrayList.add("Marakuja;Low");
        arrayList.add("Marchew;Low");
        arrayList.add("Margaryna (70% Tłuszczu);Low");
        arrayList.add("Marmolada;Low");
        arrayList.add("Masło Migdałowe;Low");
        arrayList.add("Masło Orzechowe;Low");
        arrayList.add("Masło;Low");
        arrayList.add("Maślanka;High");
        arrayList.add("Mąka Amarantowa;High");
        arrayList.add("Mąka Emmer (Farro);High");
        arrayList.add("Mąka Gryczana;Low");
        arrayList.add("Mąka Jaglana;Low");
        arrayList.add("Mąka Jęczmienna;High");
        arrayList.add("Mąka Khorasan;High");
        arrayList.add("Mąka Kokosowa;High");
        arrayList.add("Mąka Kukurydziana;Low");
        arrayList.add("Mąka Łubinowa;High");
        arrayList.add("Mąka Maniokowa;Low");
        arrayList.add("Mąka Orkiszowa;Low");
        arrayList.add("Mąka Owsiana;Low");
        arrayList.add("Mąka Pszenna;High");
        arrayList.add("Mąka Ryżowa;Low");
        arrayList.add("Mąka Samopsza;High");
        arrayList.add("Mąka Sojowa;High");
        arrayList.add("Mąka Strzałkowa;High");
        arrayList.add("Mąka Teffowa;Low");
        arrayList.add("Mąka Z Komosy Ryżowej;Low");
        arrayList.add("Mąka Z Sorgo;Low");
        arrayList.add("Mąka Z Zielonego Banana;Low");
        arrayList.add("Mąka Ze Skrobi Kukurydzianej;Low");
        arrayList.add("Mąka Żytnia;High");
        arrayList.add("Melasa Z Buraków Cukrowych;High");
        arrayList.add("Melasa Z Trzciny Cukrowej;Low");
        arrayList.add("Melony;Low");
        arrayList.add("Mennica;Low");
        arrayList.add("Mieszanka Czterech Ziaren;High");
        arrayList.add("Mięso;Low");
        arrayList.add("Migdały;Low");
        arrayList.add("Miód;High");
        arrayList.add("Mirin;Low");
        arrayList.add("Mleko Bez Laktozy;Low");
        arrayList.add("Mleko Czekoladowe;Medium");
        arrayList.add("Mleko Kokosowe;Low");
        arrayList.add("Mleko Komosa Ryżowa;Low");
        arrayList.add("Mleko Konopne;Low");
        arrayList.add("Mleko Kozie;High");
        arrayList.add("Mleko Krowie;High");
        arrayList.add("Mleko Makadamia;Low");
        arrayList.add("Mleko Migdałowe;Low");
        arrayList.add("Mleko Owsiane;High");
        arrayList.add("Mleko Ryżowe;Low");
        arrayList.add("Mleko Skondensowane;High");
        arrayList.add("Mleko Sojowe Wyprodukowane Z Białka Sojowego;Low");
        arrayList.add("Mleko Sojowe Wyprodukowane Z Ziaren Soi;High");
        arrayList.add("Młoda Kukurydza;Low");
        arrayList.add("Morele;High");
        arrayList.add("Muffinki;High");
        arrayList.add("Mus Jabłkowy;High");
        arrayList.add("Musztarda;Low");
        arrayList.add("Napoje Bezalkoholowe Zawierające Wysokofruktozowy Syrop Kukurydziany Lub Krystaliczną Fruktozę;High");
        arrayList.add("Napoje Gazowane Z Hfcs;High");
        arrayList.add("Nasiona Chia;Low");
        arrayList.add("Nasiona Dyni;Low");
        arrayList.add("Nasiona Gorczycy;Low");
        arrayList.add("Nasiona Kminku;Medium");
        arrayList.add("Nasiona Kolendry;Low");
        arrayList.add("Nasiona Konopii;Low");
        arrayList.add("Nasiona Kopru;Low");
        arrayList.add("Nasiona Kozieradki;Low");
        arrayList.add("Nasiona Lnu;Medium");
        arrayList.add("Nektarynki;High");
        arrayList.add("Nori;Low");
        arrayList.add("Ocet Balsamiczny;Medium");
        arrayList.add("Ocet Jabłkowy;Low");
        arrayList.add("Ocet Słodowy;Low");
        arrayList.add("Ocet Winny Ryżowy;Low");
        arrayList.add("Odparowany Sok Z Trzciny Cukrowej;Low");
        arrayList.add("Odsączona Ciecierzyca;Medium");
        arrayList.add("Odsączona Soczewica;Medium");
        arrayList.add("Odżywcze Płatki Drożdżowe;Low");
        arrayList.add("Ogórek;Low");
        arrayList.add("Ogórki Konserwowe;Low");
        arrayList.add("Olej Kokosowy;Low");
        arrayList.add("Olej Roślinny;Low");
        arrayList.add("Olej Rzepakowy;Low");
        arrayList.add("Olej Sezamowy;Low");
        arrayList.add("Olej Słonecznikowy;Low");
        arrayList.add("Olej Truflowy;Low");
        arrayList.add("Olej Z Awokado;High");
        arrayList.add("Olej Z Orzechów;Low");
        arrayList.add("Olej Z Otrębów Ryżowych;Low");
        arrayList.add("Olejek Czosnkowy;Low");
        arrayList.add("Oliwa Z Oliwek;Low");
        arrayList.add("Oliwki Czarne;Low");
        arrayList.add("Oliwki Zielone;Low");
        arrayList.add("Opakowanie Wonton;Low");
        arrayList.add("Opuncja;Low");
        arrayList.add("Oregano;Low");
        arrayList.add("Orkisz;High");
        arrayList.add("Orzech Kokosowy;Medium");
        arrayList.add("Orzechy Brazylijskie;Low");
        arrayList.add("Orzechy I Masła Orzechowe Z Wyjątkiem Pistacji I Orzechów Nerkowca;Medium");
        arrayList.add("Orzechy Laskowe;Medium");
        arrayList.add("Orzechy Macademia;Low");
        arrayList.add("Orzechy Nerkowca;High");
        arrayList.add("Orzechy Pekan;Low");
        arrayList.add("Orzechy Tygrysie;Low");
        arrayList.add("Orzechy Włoskie;Low");
        arrayList.add("Orzeszki Piniowe;Low");
        arrayList.add("Orzeszki Ziemne;Low");
        arrayList.add("Otręby Owsiane;Low");
        arrayList.add("Otręby Pszenne;High");
        arrayList.add("Otręby Ryżowe;Low");
        arrayList.add("Otręby;High");
        arrayList.add("Owcze Mleko;High");
        arrayList.add("Owies;Low");
        arrayList.add("Owoce W Puszce;Medium");
        arrayList.add("Pak Choi;Low");
        arrayList.add("Pandan Liście;Low");
        arrayList.add("Papaja (Suszona);High");
        arrayList.add("Papaja;Low");
        arrayList.add("Papryczka Chili Habanero;Low");
        arrayList.add("Papryczka Chili Jalapeño;Low");
        arrayList.add("Papryczka Chili Typu Chipotle;High");
        arrayList.add("Papryka (Wędzona);Low");
        arrayList.add("Papryka;Low");
        arrayList.add("Parmezan;Low");
        arrayList.add("Pasta Miso;Low");
        arrayList.add("Pasta Tahini;High");
        arrayList.add("Pasta Wasabi;Low");
        arrayList.add("Pasta Z Krewetek;Low");
        arrayList.add("Pasta Z Pigwy;Medium");
        arrayList.add("Pasta Z Tamaryndowca;Low");
        arrayList.add("Pasternak;Low");
        arrayList.add("Patisony;High");
        arrayList.add("Pełnoziarniste Płatki Zbożowe;High");
        arrayList.add("Persymony;High");
        arrayList.add("Pędy Bambusa;Low");
        arrayList.add("Pieczona Fasola;High");
        arrayList.add("Pieczywo Bezglutenowe;Low");
        arrayList.add("Pieczywo Pszenne;High");
        arrayList.add("Pieprz Czarny;Low");
        arrayList.add("Pietruszka;Low");
        arrayList.add("Pięć Przypraw;Low");
        arrayList.add("Pikle Warzywne;High");
        arrayList.add("Pistacje;High");
        arrayList.add("Piwo;Low");
        arrayList.add("Piżmian Jadalny;Medium");
        arrayList.add("Płatki Amarantowe;Medium");
        arrayList.add("Płatki Chili;Low");
        arrayList.add("Płatki Dulse;High");
        arrayList.add("Płatki Gryczane;Low");
        arrayList.add("Płatki Jęczmienne;High");
        arrayList.add("Płatki Kukurydziane;Medium");
        arrayList.add("Płatki Musli;High");
        arrayList.add("Płatki Orkiszowe;High");
        arrayList.add("Płatki Owsiane (Maks. 1/2 Szklanki);Low");
        arrayList.add("Płatki Quinoi;Low");
        arrayList.add("Płatki Ryżowe Dmuchane;Medium");
        arrayList.add("Płatki Ryżowe;Low");
        arrayList.add("Płatki Śniadaniowe Pszenne Z Suszonymi Owocami;High");
        arrayList.add("Płatki Wakame;Medium");
        arrayList.add("Polenta;Low");
        arrayList.add("Pomarańcze;Low");
        arrayList.add("Pomidor Cherry;High");
        arrayList.add("Pomidor Na Winorośli;Medium");
        arrayList.add("Pomidor Podłużny;Low");
        arrayList.add("Pomidor Rzymski;Low");
        arrayList.add("Pomidory;Low");
        arrayList.add("Popcorn;Low");
        arrayList.add("Pory;High");
        arrayList.add("Porzeczki;High");
        arrayList.add("Prażone Płatki Ryżowe;Medium");
        arrayList.add("Precelki;Low");
        arrayList.add("Produkty Pszenne, Np. Chleb, Płatki Zbożowe, Makaron;High");
        arrayList.add("Proso Łuskane;Low");
        arrayList.add("Proso;Low");
        arrayList.add("Proszek Acai;Low");
        arrayList.add("Proszek Kakaowy;Low");
        arrayList.add("Proszek Karobowy;High");
        arrayList.add("Proszek Z Trawy Pszenicznej;Low");
        arrayList.add("Przetworzone Mięso (Sprawdź Składniki);High");
        arrayList.add("Przyprawy;Medium");
        arrayList.add("Pszenica;High");
        arrayList.add("Pumpernikiel;High");
        arrayList.add("Puree Pomidorowe;Low");
        arrayList.add("Rabarbar;Low");
        arrayList.add("Rambutan;Medium");
        arrayList.add("Rampa Liście;Low");
        arrayList.add("Relish;High");
        arrayList.add("Rodzynki;High");
        arrayList.add("Rozmaryn;Low");
        arrayList.add("Rukiew Wodna;Low");
        arrayList.add("Rum;High");
        arrayList.add("Ryba;Low");
        arrayList.add("Ryż Basmanti;Low");
        arrayList.add("Ryż Biały;Low");
        arrayList.add("Ryż Brązowy;Low");
        arrayList.add("Ryż Czarny;Low");
        arrayList.add("Ryż Czerwony;Low");
        arrayList.add("Ryż Kleisty;Low");
        arrayList.add("Ryż Np. Basmati, Brązowy, Biały;Low");
        arrayList.add("Ryż;Low");
        arrayList.add("Rzepa;Low");
        arrayList.add("Rzodkiewka;Low");
        arrayList.add("Sacharyna;Low");
        arrayList.add("Sałata Koral Czerwona;Low");
        arrayList.add("Sałata Lodowa;Low");
        arrayList.add("Sałata Np. Masłowa, Góra Lodowa, Rakieta;Low");
        arrayList.add("Sałata Radicchio;Low");
        arrayList.add("Sałata Rzymska;Low");
        arrayList.add("Sałata;Low");
        arrayList.add("Sardynki;Low");
        arrayList.add("Seler;Low");
        arrayList.add("Ser Amerykański;Medium");
        arrayList.add("Ser Brie;Low");
        arrayList.add("Ser Camembert;Low");
        arrayList.add("Ser Cheddar;Low");
        arrayList.add("Ser Chevre;Low");
        arrayList.add("Ser Colby;Low");
        arrayList.add("Ser Feta;Low");
        arrayList.add("Ser Gruyere;Low");
        arrayList.add("Ser Halloumi;Medium");
        arrayList.add("Ser Havarti;Low");
        arrayList.add("Ser Kozi;Low");
        arrayList.add("Ser Manchego;Low");
        arrayList.add("Ser Mascarpone;Medium");
        arrayList.add("Ser Monterey Jack;Low");
        arrayList.add("Ser Mozzarella;Low");
        arrayList.add("Ser Paneer;Low");
        arrayList.add("Ser Pecorino;Low");
        arrayList.add("Ser Ricotta;Medium");
        arrayList.add("Ser Sojowy;Low");
        arrayList.add("Ser Szwajcarski;Low");
        arrayList.add("Ser Śmietanowy;Medium");
        arrayList.add("Ser Twarożek;Low");
        arrayList.add("Ser Twaróg;Medium");
        arrayList.add("Ser Wegański Na Bazie Oleju Kokosowego;Low");
        arrayList.add("Serce Palmy;Low");
        arrayList.add("Serek Topiony;Medium");
        arrayList.add("Serek Wiejski Bez Laktozy;Low");
        arrayList.add("Sery Twarde Lub Dojrzałe;Low");
        arrayList.add("Siemię Lniane;Low");
        arrayList.add("Skrobia Kukurydziana;Low");
        arrayList.add("Skrobia Z Tapioki;Low");
        arrayList.add("Skrobia Ziemniaczana;Low");
        arrayList.add("Skrystalizowana Fruktoza;High");
        arrayList.add("Słodka Kukurydza;High");
        arrayList.add("Słodki Ziemniak;Low");
        arrayList.add("Smoczy Owoc;Low");
        arrayList.add("Soczewica (Gotowana);Medium");
        arrayList.add("Soczewica (Konserwowa);Low");
        arrayList.add("Soczewica Konserwowa;Medium");
        arrayList.add("Soczewica;High");
        arrayList.add("Soja (Jedwabiste Tofu, Teksturowane Białko Roślinne, Edamame, Orzechy Sojowe, Mleko Sojowe);High");
        arrayList.add("Sok Cytrynowy;Low");
        arrayList.add("Sok Gruszkowy;High");
        arrayList.add("Sok Jabłkowy;High");
        arrayList.add("Sok Jagodowy;High");
        arrayList.add("Sok Owocowy;High");
        arrayList.add("Sok Pomarańczowy (Maks. 125Ml);Low");
        arrayList.add("Sok Pomarańczowy;High");
        arrayList.add("Sok Z Limonki;Low");
        arrayList.add("Sok Z Mango;High");
        arrayList.add("Sok Z Mieszanki Warzywnej;Low");
        arrayList.add("Sok Żurawinowy;Low");
        arrayList.add("Sorbitol;High");
        arrayList.add("Sos Barbecue;Low");
        arrayList.add("Sos Chrzanowy;Low");
        arrayList.add("Sos Do Makaronu (Na Bazie Śmietanki);High");
        arrayList.add("Sos Miętowy;Low");
        arrayList.add("Sos Pesto;Medium");
        arrayList.add("Sos Pomidorowy;Low");
        arrayList.add("Sos Rybny;Low");
        arrayList.add("Sos Słodko-Kwaśny;Low");
        arrayList.add("Sos Sojowy;Low");
        arrayList.add("Sos Worcestershire;Low");
        arrayList.add("Sos Z Ostryg;Low");
        arrayList.add("Spadź;Low");
        arrayList.add("Spirulina W Proszku;Low");
        arrayList.add("Stewia W Proszku;Low");
        arrayList.add("Stewia;Low");
        arrayList.add("Strąki Ziaren Wanilii;Low");
        arrayList.add("Sukraloza;Low");
        arrayList.add("Sułtanki;High");
        arrayList.add("Sum Choi;Low");
        arrayList.add("Surowy Cukier;Low");
        arrayList.add("Suszone Owoce (Np. Rodzynki, Daktyle);High");
        arrayList.add("Suszone Pomidory;Medium");
        arrayList.add("Syrop Glukozo-Fruktozowy(High Fructose Corn Syrup – HFCS);High");
        arrayList.add("Syrop Klonowy;Low");
        arrayList.add("Syrop Kukurydziany O Wysokiej Zawartości Frukozy (HFCS);High");
        arrayList.add("Syrop Kukurydziany;Low");
        arrayList.add("Syrop Melasowy;High");
        arrayList.add("Syrop Z Agawy;High");
        arrayList.add("Syrop Z Brązowego Ryżu;Low");
        arrayList.add("Syrop Ze Słodu Ryżowego;Low");
        arrayList.add("Szafran;Low");
        arrayList.add("Szalotki;Medium");
        arrayList.add("Szałwia;Low");
        arrayList.add("Szczypiorek Azjatycki;Low");
        arrayList.add("Szczypiorek;Low");
        arrayList.add("Szparagi;High");
        arrayList.add("Szpinak;Low");
        arrayList.add("Śliwki;High");
        arrayList.add("Śmietana (Kwaśna);Medium");
        arrayList.add("Śmietana (Ponad 2 Łyżki);High");
        arrayList.add("Śmietana (Zwykła);Medium");
        arrayList.add("Śmietana;Medium");
        arrayList.add("Tacosy;Low");
        arrayList.add("Tamarillo;High");
        arrayList.add("Tamaryndowiec;Low");
        arrayList.add("Tangelos;Low");
        arrayList.add("Taro;Low");
        arrayList.add("Tempeh;Low");
        arrayList.add("Tequila;Low");
        arrayList.add("Tofu (Jedwabiste);High");
        arrayList.add("Tofu (Twarde);Low");
        arrayList.add("Tofu (Zwykłe);Low");
        arrayList.add("Tortilla;Low");
        arrayList.add("Trawa Cytrynowa;Low");
        arrayList.add("Truskawki;Low");
        arrayList.add("Tuńczyk;Low");
        arrayList.add("Twarde I Średnie Tofu;Low");
        arrayList.add("Twarożek;Low");
        arrayList.add("Tymianek;Low");
        arrayList.add("Verjuice;Low");
        arrayList.add("Wafle Ryżowe;Low");
        arrayList.add("Wegemit;Low");
        arrayList.add("Wędliny M.In. Szynka I Pierś Z Indyka;Low");
        arrayList.add("Whisky;Low");
        arrayList.add("Wieprzowina;Low");
        arrayList.add("Wino (Białe);Low");
        arrayList.add("Wino (Lepkie);High");
        arrayList.add("Wino (Maksymalnie Jedno);Low");
        arrayList.add("Wino (Musujące);Low");
        arrayList.add("Wino (Słodkie);Low");
        arrayList.add("Winogrona Białe;Medium");
        arrayList.add("Winogrona Czerwone;Medium");
        arrayList.add("Winogrona Zielone;Medium");
        arrayList.add("Wiosenne Zielenie;Low");
        arrayList.add("Wiśnie;High");
        arrayList.add("Woda Kokosowa;High");
        arrayList.add("Woda;Low");
        arrayList.add("Wołowina;Low");
        arrayList.add("Wódka;Low");
        arrayList.add("Zarodki Pszenicy;High");
        arrayList.add("Ziarenka Sezamu;Low");
        arrayList.add("Ziarna Jęczmienia Perłowego;Low");
        arrayList.add("Ziarna Słonecznika;Low");
        arrayList.add("Ziarna Żyta;High");
        arrayList.add("Ziarno Pszenicy;High");
        arrayList.add("Zielona Papryka;High");
        arrayList.add("Zielone Fasolki;Low");
        arrayList.add("Zielony Groszek;Medium");
        arrayList.add("Zielony Pieprz;Low");
        arrayList.add("Ziemniak;Low");
        arrayList.add("Złoty Syrop;Medium");
        arrayList.add("Zwykły Biszkopt;Low");
        arrayList.add("Żurawina;Medium");
        arrayList.add("Żyto;High");
        arrayList.add("Żywność Bezglutenowa, Np. Pieczywo, Makarony;Low");
        
        adapter = new CustomListAdapter(this , R.layout.custom_list , arrayList);

        myListView.setAdapter(adapter);

        searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String s) {
                return false;
            }

            @Override
            public boolean onQueryTextChange(String s) {
                adapter.getFilter().filter(s);
                return false;
            }
        });
    }
}